/**
 * Pre-configured professional design presets
 */
export const DesignPresets = [
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    desc: 'Sleek dark gradient with glowing cyan eyes',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#38bdf8',
    dotsGradientColor: '#818cf8',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#38bdf8',
    cornerDotType: 'dot',
    cornerDotColor: '#818cf8',
    background: '#0f172a',
    frame: 'none'
  },
  {
    id: 'emerald-glass',
    name: 'Emerald Glass',
    desc: 'Fresh mint and emerald green aesthetic',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#065f46',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'classy',
    cornerSquareColor: '#059669',
    cornerDotType: 'classy',
    cornerDotColor: '#10b981',
    background: '#f0fdf4',
    frame: 'bottom-badge',
    frameText: 'SCAN TO OPEN',
    frameColor: '#059669',
    frameTextColor: '#ffffff'
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    desc: 'Luxury metallic gold on deep onyx',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#f59e0b',
    dotsGradientColor: '#d97706',
    gradientType: 'radial',
    gradientRotation: 0,
    cornerSquareType: 'classy',
    cornerSquareColor: '#f59e0b',
    cornerDotType: 'classy',
    cornerDotColor: '#fbbf24',
    background: '#18181b',
    frame: 'none'
  },
  {
    id: 'cyber-neon',
    name: 'Cyberpunk Neon',
    desc: 'Vibrant magenta and violet glow',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#ec4899',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'dot',
    cornerSquareColor: '#ec4899',
    cornerDotType: 'dot',
    cornerDotColor: '#8b5cf6',
    background: '#09090b',
    frame: 'card-border',
    frameText: 'SCAN ME',
    frameColor: '#ec4899',
    frameTextColor: '#ffffff'
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Clean',
    desc: 'Trustworthy navy and royal blue palette',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#1e40af',
    dotsGradientColor: '#3b82f6',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#1e3a8a',
    cornerDotType: 'dot',
    cornerDotColor: '#2563eb',
    background: '#ffffff',
    frame: 'bottom-badge',
    frameText: 'SCAN FOR INFO',
    frameColor: '#1e40af',
    frameTextColor: '#ffffff'
  },
  {
    id: 'sunset-vibrant',
    name: 'Sunset Glow',
    desc: 'Warm orange and coral red gradient',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#e11d48',
    cornerDotType: 'dot',
    cornerDotColor: '#f97316',
    background: '#fff7ed',
    frame: 'top-banner',
    frameText: 'DISCOVER MORE',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff'
  },
  {
    id: 'minimalist-mono',
    name: 'Minimalist Mono',
    desc: 'Crisp high-contrast pure black and white',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    dotsGradientColor: '#000000',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'none'
  },
  {
    id: 'pastel-violet',
    name: 'Pastel Lavender',
    desc: 'Soft lilac and purple for modern brands',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#8b5cf6',
    dotsGradientColor: '#a855f7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#7c3aed',
    cornerDotType: 'dot',
    cornerDotColor: '#a855f7',
    background: '#faf5ff',
    frame: 'bottom-badge',
    frameText: 'SCAN ME',
    frameColor: '#7c3aed',
    frameTextColor: '#ffffff'
  }
];
