/**
 * Categorized pre-configured design presets (48 presets across 6 categories)
 * Categories: 'cool', 'professional', 'simple', 'gaming', 'memes', 'cringe'
 */
export const DesignPresets = [
  // ==========================================
  // 1. COOL PRESETS (8 Designs)
  // ==========================================
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    desc: 'Sleek dark gradient with glowing cyan eyes',
    category: 'cool',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#38bdf8',
    dotsGradientColor: '#818cf8',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#38bdf8',
    cornerDotType: 'dot',
    cornerDotColor: '#818cf8',
    background: '#0f172a',
    frame: 'none'
  },
  {
    id: 'cyber-neon',
    name: 'Cyberpunk Neon',
    desc: 'Vibrant magenta and violet glow',
    category: 'cool',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#ec4899',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'dot',
    cornerSquareColor: '#ec4899',
    cornerDotType: 'dot',
    cornerDotColor: '#8b5cf6',
    background: '#09090b',
    frame: 'card-border',
    frameText: 'SCAN ME',
    frameColor: '#ec4899',
    frameTextColor: '#ffffff'
  },
  {
    id: 'sunset-vibrant',
    name: 'Sunset Glow',
    desc: 'Warm orange and coral red gradient',
    category: 'cool',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#e11d48',
    cornerDotType: 'dot',
    cornerDotColor: '#f97316',
    background: '#fff7ed',
    frame: 'top-banner',
    frameText: 'DISCOVER MORE',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-ocean',
    name: 'Deep Ocean Blue',
    desc: 'Mystic aquamarine and midnight teal gradient',
    category: 'cool',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#06b6d4',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'classy',
    cornerSquareColor: '#0891b2',
    cornerDotType: 'dot',
    cornerDotColor: '#38bdf8',
    background: '#042f2e',
    frame: 'bottom-badge',
    frameText: 'DISCOVER',
    frameColor: '#0891b2',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-aurora',
    name: 'Aurora Borealis',
    desc: 'Electric green and celestial teal glow',
    category: 'cool',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#06b6d4',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#10b981',
    cornerDotType: 'dot',
    cornerDotColor: '#2dd4bf',
    background: '#022c22',
    frame: 'none'
  },
  {
    id: 'cool-carbon',
    name: 'Carbon Fiber Slate',
    desc: 'High-tech dark carbon weave',
    category: 'cool',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#94a3b8',
    dotsGradientColor: '#cbd5e1',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#f8fafc',
    cornerDotType: 'square',
    cornerDotColor: '#cbd5e1',
    background: '#0f172a',
    frame: 'card-border',
    frameText: 'SCAN CODE',
    frameColor: '#475569',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-nebula',
    name: 'Galaxy Nebula',
    desc: 'Radial cosmic pink and violet starlight',
    category: 'cool',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#f43f5e',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'radial',
    gradientRotation: 0,
    cornerSquareType: 'classy',
    cornerSquareColor: '#f43f5e',
    cornerDotType: 'classy',
    cornerDotColor: '#fb7185',
    background: '#1e1b4b',
    frame: 'none'
  },
  {
    id: 'cool-ice',
    name: 'Frosted Glacial Ice',
    desc: 'Chilled ice blue on crisp porcelain',
    category: 'cool',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#38bdf8',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0284c7',
    cornerDotType: 'dot',
    cornerDotColor: '#7dd3fc',
    background: '#f0f9ff',
    frame: 'bottom-badge',
    frameText: 'OPEN LINK',
    frameColor: '#0284c7',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 2. PROFESSIONAL PRESETS (8 Designs)
  // ==========================================
  {
    id: 'emerald-glass',
    name: 'Emerald Glass',
    desc: 'Fresh mint and emerald green aesthetic',
    category: 'professional',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#065f46',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'classy',
    cornerSquareColor: '#059669',
    cornerDotType: 'classy',
    cornerDotColor: '#10b981',
    background: '#f0fdf4',
    frame: 'bottom-badge',
    frameText: 'SCAN TO OPEN',
    frameColor: '#059669',
    frameTextColor: '#ffffff'
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    desc: 'Luxury metallic gold on deep onyx',
    category: 'professional',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#f59e0b',
    dotsGradientColor: '#d97706',
    gradientType: 'radial',
    gradientRotation: 0,
    cornerSquareType: 'classy',
    cornerSquareColor: '#f59e0b',
    cornerDotType: 'classy',
    cornerDotColor: '#fbbf24',
    background: '#18181b',
    frame: 'none'
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Clean',
    desc: 'Trustworthy navy and royal blue palette',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#1e40af',
    dotsGradientColor: '#3b82f6',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#1e3a8a',
    cornerDotType: 'dot',
    cornerDotColor: '#2563eb',
    background: '#ffffff',
    frame: 'bottom-badge',
    frameText: 'SCAN FOR INFO',
    frameColor: '#1e40af',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-slate',
    name: 'Executive Slate',
    desc: 'Sophisticated charcoal grey for corporate documents',
    category: 'professional',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#334155',
    dotsGradientColor: '#334155',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'square',
    cornerDotColor: '#475569',
    background: '#f8fafc',
    frame: 'none'
  },
  {
    id: 'professional-wine',
    name: 'Bordeaux Burgundy',
    desc: 'Rich wine red and gold accent luxury branding',
    category: 'professional',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#881337',
    dotsGradientColor: '#be123c',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#881337',
    cornerDotType: 'classy',
    cornerDotColor: '#fb7185',
    background: '#fff1f2',
    frame: 'bottom-badge',
    frameText: 'EXCLUSIVE ACCESS',
    frameColor: '#881337',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-silver',
    name: 'Platinum Executive',
    desc: 'Silver metallic sheen on deep slate background',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#e2e8f0',
    dotsGradientColor: '#94a3b8',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#cbd5e1',
    cornerDotType: 'dot',
    cornerDotColor: '#ffffff',
    background: '#0f172a',
    frame: 'card-border',
    frameText: 'OFFICIAL RECORD',
    frameColor: '#334155',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-rosegold',
    name: 'Luxe Rose Gold',
    desc: 'Warm rose champagne tone for boutique products',
    category: 'professional',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#fb7185',
    dotsGradientColor: '#f43f5e',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#e11d48',
    cornerDotType: 'classy',
    cornerDotColor: '#fda4af',
    background: '#fff1f2',
    frame: 'bottom-badge',
    frameText: 'SCAN TO VIEW MENU',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-teal',
    name: 'Enterprise Teal',
    desc: 'Modern healthcare & finance teal theme',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#0f766e',
    dotsGradientColor: '#14b8a6',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0f766e',
    cornerDotType: 'dot',
    cornerDotColor: '#2dd4bf',
    background: '#f0fdfa',
    frame: 'bottom-badge',
    frameText: 'VERIFIED PORTAL',
    frameColor: '#0f766e',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 3. SIMPLE PRESETS (8 Designs)
  // ==========================================
  {
    id: 'minimalist-mono',
    name: 'Minimalist Mono',
    desc: 'Crisp high-contrast pure black and white',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    dotsGradientColor: '#000000',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'none'
  },
  {
    id: 'pastel-violet',
    name: 'Pastel Lavender',
    desc: 'Soft lilac and purple for modern brands',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#8b5cf6',
    dotsGradientColor: '#a855f7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#7c3aed',
    cornerDotType: 'dot',
    cornerDotColor: '#a855f7',
    background: '#faf5ff',
    frame: 'bottom-badge',
    frameText: 'SCAN ME',
    frameColor: '#7c3aed',
    frameTextColor: '#ffffff'
  },
  {
    id: 'simple-peach',
    name: 'Pastel Peach',
    desc: 'Warm cream and soft apricot tone',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#ea580c',
    dotsGradientColor: '#ea580c',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#c2410c',
    cornerDotType: 'dot',
    cornerDotColor: '#f97316',
    background: '#fff7ed',
    frame: 'none'
  },
  {
    id: 'simple-mint',
    name: 'Clean Sage Mint',
    desc: 'Gentle organic green on soft off-white',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#15803d',
    dotsGradientColor: '#15803d',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#166534',
    cornerDotType: 'dot',
    cornerDotColor: '#22c55e',
    background: '#f0fdf4',
    frame: 'none'
  },
  {
    id: 'simple-charcoal',
    name: 'Charcoal Minimal',
    desc: 'Clean dark slate on ivory grey paper',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#1e293b',
    dotsGradientColor: '#1e293b',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'square',
    cornerDotColor: '#334155',
    background: '#f1f5f9',
    frame: 'none'
  },
  {
    id: 'simple-sky',
    name: 'Soft Sky Blue',
    desc: 'Light blue tones for subtle print stickers',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#0284c7',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0369a1',
    cornerDotType: 'dot',
    cornerDotColor: '#38bdf8',
    background: '#f0f9ff',
    frame: 'none'
  },
  {
    id: 'simple-dark-mono',
    name: 'Dark Mode Pure',
    desc: 'Crisp white dots on dark night surface',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#ffffff',
    dotsGradientColor: '#ffffff',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#ffffff',
    cornerDotType: 'square',
    cornerDotColor: '#ffffff',
    background: '#090d16',
    frame: 'none'
  },
  {
    id: 'simple-rose',
    name: 'Soft Rose Quartz',
    desc: 'Elegant muted pink on pale rose background',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#e11d48',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#be123c',
    cornerDotType: 'dot',
    cornerDotColor: '#fb7185',
    background: '#fff1f2',
    frame: 'none'
  },

  // ==========================================
  // 4. GAMING PRESETS (8 Designs)
  // ==========================================
  {
    id: 'gaming-razer',
    name: 'Toxic Chroma Green',
    desc: 'Electric esports neon green on stealth black',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#22c55e',
    dotsGradientColor: '#10b981',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'square',
    cornerSquareColor: '#22c55e',
    cornerDotType: 'square',
    cornerDotColor: '#4ade80',
    background: '#050505',
    frame: 'card-border',
    frameText: 'JOIN LOBBY',
    frameColor: '#22c55e',
    frameTextColor: '#000000'
  },
  {
    id: 'gaming-ps',
    name: 'Console Blue LED',
    desc: 'Royal gaming blue and cyan controller vibe',
    category: 'gaming',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#3b82f6',
    dotsGradientColor: '#06b6d4',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'dot',
    cornerSquareColor: '#2563eb',
    cornerDotType: 'dot',
    cornerDotColor: '#60a5fa',
    background: '#090d16',
    frame: 'bottom-badge',
    frameText: 'PRESS START',
    frameColor: '#2563eb',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-rog',
    name: 'ROG Crimson Core',
    desc: 'Aggressive gaming red and metallic obsidian',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#ef4444',
    dotsGradientColor: '#b91c1c',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'square',
    cornerSquareColor: '#dc2626',
    cornerDotType: 'square',
    cornerDotColor: '#fca5a5',
    background: '#09090b',
    frame: 'top-banner',
    frameText: 'LEVEL UP',
    frameColor: '#dc2626',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-cyberpunk2077',
    name: 'Night City Yellow',
    desc: 'Futuristic high-voltage yellow & dark gunmetal',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#facc15',
    dotsGradientColor: '#facc15',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#eab308',
    cornerDotType: 'square',
    cornerDotColor: '#fef08a',
    background: '#18181b',
    frame: 'bottom-badge',
    frameText: 'HACK DATA',
    frameColor: '#facc15',
    frameTextColor: '#000000'
  },
  {
    id: 'gaming-twitch',
    name: 'Streamer Purple',
    desc: 'Vibrant livestream purple & violet starlight',
    category: 'gaming',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#9333ea',
    dotsGradientColor: '#c084fc',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#7e22ce',
    cornerDotType: 'dot',
    cornerDotColor: '#e9d5ff',
    background: '#1e1b4b',
    frame: 'bottom-badge',
    frameText: 'WATCH LIVE',
    frameColor: '#9333ea',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-retro-arcade',
    name: 'Retro 8-Bit Arcade',
    desc: 'Pixelated orange and yellow 80s arcade vibe',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#facc15',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#ea580c',
    cornerDotType: 'square',
    cornerDotColor: '#fde047',
    background: '#172554',
    frame: 'card-border',
    frameText: 'INSERT COIN',
    frameColor: '#f97316',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-pipboy',
    name: 'Fallout Terminal Green',
    desc: 'Retro CRT phosphor green on dark bunker monitor',
    category: 'gaming',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#4ade80',
    dotsGradientColor: '#4ade80',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'dot',
    cornerSquareColor: '#22c55e',
    cornerDotType: 'dot',
    cornerDotColor: '#86efac',
    background: '#022c22',
    frame: 'top-banner',
    frameText: 'VAULT TEC DATA',
    frameColor: '#15803d',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-discord',
    name: 'Discord Squad',
    desc: 'Blurple & dark chat room gamer aesthetic',
    category: 'gaming',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#5865f2',
    dotsGradientColor: '#818cf8',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#5865f2',
    cornerDotType: 'dot',
    cornerDotColor: '#c7d2fe',
    background: '#1e1f22',
    frame: 'bottom-badge',
    frameText: 'JOIN DISCORD',
    frameColor: '#5865f2',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 5. INDIAN MEMES PRESETS (8 Designs)
  // ==========================================
  {
    id: 'meme-paisa-double',
    name: '25 Din Me Paisa Double',
    desc: 'Laxmi Chit Fund Special Mint Green & Gold',
    category: 'memes',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#b45309',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#059669',
    cornerDotType: 'classy',
    cornerDotColor: '#d97706',
    background: '#ecfdf5',
    frame: 'bottom-badge',
    frameText: 'PAISA DOUBLE',
    frameColor: '#059669',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-hazrat',
    name: 'Hazrat Hazrat',
    desc: 'Wasseypur raw charcoal & red alert style',
    category: 'memes',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#dc2626',
    dotsGradientColor: '#1f2937',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#991b1b',
    cornerDotType: 'square',
    cornerDotColor: '#111827',
    background: '#f8fafc',
    frame: 'top-banner',
    frameText: 'HAZRAT HAZRAT',
    frameColor: '#dc2626',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-jethalal',
    name: 'Babuchak Jethalal',
    desc: 'Gada Electronics yellow & bright purple style',
    category: 'memes',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#eab308',
    dotsGradientColor: '#a855f7',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#ca8a04',
    cornerDotType: 'dot',
    cornerDotColor: '#7e22ce',
    background: '#fffbeb',
    frame: 'bottom-badge',
    frameText: 'HEY MAA MATAJI',
    frameColor: '#ca8a04',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-mirzapur',
    name: 'Kaleen Bhaiya Royal',
    desc: 'Mirzapur carpet velvet red & gold bullion',
    category: 'memes',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#991b1b',
    dotsGradientColor: '#d97706',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#7f1d1d',
    cornerDotType: 'classy',
    cornerDotColor: '#f59e0b',
    background: '#18181b',
    frame: 'bottom-badge',
    frameText: 'MIRZAPUR KING',
    frameColor: '#991b1b',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-bulldozer',
    name: 'Bulldozer Alert',
    desc: 'High-visibility construction saffron orange',
    category: 'memes',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#ea580c',
    dotsGradientColor: '#ca8a04',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#c2410c',
    cornerDotType: 'square',
    cornerDotColor: '#eab308',
    background: '#fff7ed',
    frame: 'top-banner',
    frameText: 'RAASTA SAAF',
    frameColor: '#ea580c',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-binod',
    name: 'Binod Special',
    desc: 'Simple rural clay mud brown & teal style',
    category: 'memes',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#78350f',
    dotsGradientColor: '#78350f',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'dot',
    cornerSquareColor: '#92400e',
    cornerDotType: 'dot',
    cornerDotColor: '#d97706',
    background: '#fef3c7',
    frame: 'bottom-badge',
    frameText: 'BINOD WAS HERE',
    frameColor: '#78350f',
    frameTextColor: '#ffffff'
  },
  {
    id: 'meme-kgf',
    name: 'KGF Monster Gold',
    desc: 'Rocky Bhai dusty gold mines obsidian style',
    category: 'memes',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#d97706',
    dotsGradientColor: '#b45309',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#b45309',
    cornerDotType: 'classy',
    cornerDotColor: '#f59e0b',
    background: '#09090b',
    frame: 'card-border',
    frameText: 'VIOLENCE VIOLENCE',
    frameColor: '#d97706',
    frameTextColor: '#000000'
  },
  {
    id: 'meme-mitron',
    name: 'Mitron Saffron Glow',
    desc: 'National tricolor vibrant saffron & emerald',
    category: 'memes',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#16a34a',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#ea580c',
    cornerDotType: 'dot',
    cornerDotColor: '#15803d',
    background: '#ffffff',
    frame: 'bottom-badge',
    frameText: 'MITRON SCAN KARO',
    frameColor: '#f97316',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 6. CRINGE PRESETS (8 Designs)
  // ==========================================
  {
    id: 'cringe-eye-bleeder',
    name: 'Eye Bleeder',
    desc: 'Hot pink on neon green (Scannability Warning!)',
    category: 'cringe',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#ff007f',
    dotsGradientColor: '#ff00ff',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'square',
    cornerSquareColor: '#ff007f',
    cornerDotType: 'square',
    cornerDotColor: '#ff00ff',
    background: '#39ff14',
    frame: 'none'
  },
  {
    id: 'cringe-uncanny',
    name: 'Uncanny Cringe',
    desc: 'Wild vomit brown dots on neon yellow background',
    category: 'cringe',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#78350f',
    dotsGradientColor: '#b45309',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'dot',
    cornerSquareColor: '#78350f',
    cornerDotType: 'dot',
    cornerDotColor: '#fef08a',
    background: '#facc15',
    frame: 'bottom-badge',
    frameText: 'CRINGE ALERT',
    frameColor: '#78350f',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cringe-comic',
    name: 'Comic Cringe',
    desc: 'Awkward framing with mismatched blue and orange',
    category: 'cringe',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#2563eb',
    dotsGradientColor: '#f97316',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#1e3a8a',
    cornerDotType: 'dot',
    cornerDotColor: '#ea580c',
    background: '#fffbeb',
    frame: 'top-banner',
    frameText: 'DONT SCAN ME',
    frameColor: '#1e3a8a',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cringe-vaporwave',
    name: 'Vaporwave Mashup',
    desc: 'Oversaturated cyan, magenta and yellow clash',
    category: 'cringe',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#06b6d4',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'dot',
    cornerSquareColor: '#a855f7',
    cornerDotType: 'dot',
    cornerDotColor: '#facc15',
    background: '#f472b6',
    frame: 'card-border',
    frameText: 'A E S T H E T I C',
    frameColor: '#a855f7',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cringe-grey',
    name: 'Invisible Low Contrast',
    desc: 'Light grey dots on lighter grey (Unscannable Test)',
    category: 'cringe',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#cbd5e1',
    dotsGradientColor: '#cbd5e1',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#cbd5e1',
    cornerDotType: 'square',
    cornerDotColor: '#cbd5e1',
    background: '#e2e8f0',
    frame: 'none'
  },
  {
    id: 'cringe-paint',
    name: 'MS Paint 1998',
    desc: 'Pure RGB primary red, blue and yellow chaos',
    category: 'cringe',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#ff0000',
    dotsGradientColor: '#0000ff',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#00ff00',
    cornerDotType: 'square',
    cornerDotColor: '#ffff00',
    background: '#ffffff',
    frame: 'bottom-badge',
    frameText: 'GRAPHICS DESIGN IS MY PASSION',
    frameColor: '#ff0000',
    frameTextColor: '#ffff00'
  },
  {
    id: 'cringe-redalert',
    name: 'Flash Hazard',
    desc: 'High contrast electric purple dots on bright red',
    category: 'cringe',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#7e22ce',
    dotsGradientColor: '#7e22ce',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'dot',
    cornerSquareColor: '#581c87',
    cornerDotType: 'dot',
    cornerDotColor: '#c084fc',
    background: '#ef4444',
    frame: 'none'
  },
  {
    id: 'cringe-glitch',
    name: 'Toxic Swamp Cringe',
    desc: 'Dark olive green with muddy mustard yellow dots',
    category: 'cringe',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#84cc16',
    dotsGradientColor: '#713f12',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#365314',
    cornerDotType: 'classy',
    cornerDotColor: '#a16207',
    background: '#ecfccb',
    frame: 'bottom-badge',
    frameText: 'SWAMP QR',
    frameColor: '#365314',
    frameTextColor: '#ffffff'
  }
];
