/**
 * Categorized pre-configured design presets
 * Categories: 'templates', 'cool', 'professional', 'simple', 'gaming', 'memes', 'cringe'
 */
export const DesignPresets = [
  // ==========================================
  // 0. FEATURED DESIGNER TEMPLATES (From User Showcase)
  // ==========================================
  {
    id: 'template-tiktok',
    name: 'TikTok Vibrant',
    desc: 'Black & cyber red accented dots with TikTok center icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#fe2c55',
    cornerDotType: 'square',
    cornerDotColor: '#00f2fe',
    background: '#ffffff',
    logoBrand: 'tiktok',
    frame: 'none'
  },
  {
    id: 'template-dropbox',
    name: 'Dropbox Download',
    desc: 'Blue circular badge with "Download now" pill',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0061ff',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0061ff',
    cornerDotType: 'dot',
    cornerDotColor: '#0061ff',
    background: '#ffffff',
    logoBrand: 'dropbox',
    frame: 'circle-badge',
    frameText: 'Download now',
    frameColor: '#0061ff',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-crimson-dots',
    name: 'Crimson Burgundy Dots',
    desc: 'Luxurious burgundy & rose dotted modern aesthetic',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#881337',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#881337',
    cornerDotType: 'dot',
    cornerDotColor: '#e11d48',
    background: '#fff1f2',
    frame: 'none'
  },
  {
    id: 'template-google-maps',
    name: 'Google Maps Arrival',
    desc: 'Red corner brackets with Google Maps pin icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#1e293b',
    cornerSquareType: 'dot',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'maps',
    frame: 'corner-brackets',
    frameText: 'How to arrive',
    frameColor: '#ea4335',
    frameTextColor: '#ea4335'
  },
  {
    id: 'template-wifi-hexagon',
    name: 'WiFi Hexagon Badge',
    desc: 'Geometric hexagon frame with "Connect to our WiFi" pill',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'wifi',
    frame: 'hexagon-badge',
    frameText: 'Connect to our WiFi',
    frameColor: '#000000',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-paypal-brackets',
    name: 'PayPal Blue Brackets',
    desc: 'Sky blue corner brackets with PayPal official branding',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#0079c1',
    dotsGradientColor: '#00457c',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0079c1',
    cornerDotType: 'dot',
    cornerDotColor: '#00457c',
    background: '#ffffff',
    logoBrand: 'paypal',
    frame: 'corner-brackets',
    frameText: 'Paypal',
    frameColor: '#0079c1',
    frameTextColor: '#0079c1'
  },
  {
    id: 'template-linkedin-connect',
    name: 'LinkedIn Connect Ribbon',
    desc: 'Professional corporate blue with 3D folded ribbon banner',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0a66c2',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0a66c2',
    cornerDotType: 'dot',
    cornerDotColor: '#0a66c2',
    background: '#ffffff',
    logoBrand: 'linkedin',
    frame: 'ribbon',
    frameText: 'Connect',
    frameColor: '#0a66c2',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-wikipedia-readme',
    name: 'Wikipedia Read Me',
    desc: 'Slate charcoal ribbon banner with Wikipedia emblem',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#1e293b',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'square',
    cornerDotColor: '#1e293b',
    background: '#ffffff',
    logoBrand: 'wikipedia',
    frame: 'ribbon',
    frameText: 'Read me',
    frameColor: '#475569',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-twitch-channel',
    name: 'Twitch Channel Live',
    desc: 'Bright purple livestream aesthetic with Twitch logo',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#9146ff',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#9146ff',
    cornerDotType: 'dot',
    cornerDotColor: '#9146ff',
    background: '#ffffff',
    logoBrand: 'twitch',
    frame: 'bottom-badge',
    frameText: 'Twitch Channel',
    frameColor: '#9146ff',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-paypal-ribbon',
    name: 'PayPal Ribbon Blue',
    desc: 'Cyan blue theme with 3D Paypal folded ribbon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#0284c7',
    dotsGradientColor: '#0369a1',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0284c7',
    cornerDotType: 'dot',
    cornerDotColor: '#0369a1',
    background: '#ffffff',
    logoBrand: 'paypal',
    frame: 'ribbon',
    frameText: 'Paypal',
    frameColor: '#0284c7',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-vcard-ribbon',
    name: 'vCard Contact Ribbon',
    desc: 'Magenta purple ribbon banner for digital contact cards',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#c026d3',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#a21caf',
    cornerDotType: 'dot',
    cornerDotColor: '#c026d3',
    background: '#ffffff',
    logoBrand: 'contact',
    frame: 'ribbon',
    frameText: 'vCard',
    frameColor: '#c026d3',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-pinterest-follow',
    name: 'Pinterest Follow Us',
    desc: 'Deep crimson arch card with Pinterest logo and script CTA',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'dot',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'pinterest',
    frame: 'arch-card',
    frameText: 'Follow us',
    frameColor: '#bd081c',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-pinterest-target',
    name: 'Pinterest Target Radar',
    desc: 'High-contrast red circular accents with Pinterest pin',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'dot',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'pinterest',
    frame: 'dashed-circle',
    frameColor: '#bd081c'
  },
  {
    id: 'template-spotify-playlist',
    name: 'Spotify Playlist Circle',
    desc: 'Black circular ring frame with "My playlist" pill and Spotify logo',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#10b981',
    cornerSquareType: 'dot',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'spotify',
    frame: 'circle-badge',
    frameText: 'My playlist',
    frameColor: '#000000',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-messenger-chat',
    name: 'Messenger Gradient Bubble',
    desc: 'Purple-pink circular gradient with Messenger chat icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#ec4899',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#8b5cf6',
    background: '#ffffff',
    logoBrand: 'messenger',
    frame: 'circle-outline',
    frameColor: '#ec4899'
  },
  {
    id: 'template-bitcoin-pay',
    name: 'Bitcoin Crypto Card',
    desc: 'High-visibility crypto gold card with "Pay in Bitcoin"',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'bitcoin',
    frame: 'card-border',
    frameText: 'Pay in Bitcoin',
    frameColor: '#f97316',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-youtube-play',
    name: 'YouTube Play Video',
    desc: 'Obsidian card with red rounded corner eyes & "Play video"',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#ef4444',
    cornerDotType: 'dot',
    cornerDotColor: '#ef4444',
    background: '#ffffff',
    logoBrand: 'youtube',
    frame: 'card-border',
    frameText: 'Play video',
    frameColor: '#000000',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-wifi-connect',
    name: 'WiFi Connect Card',
    desc: 'Clean platinum card with "Connect WIFI" bottom badge',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#334155',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#334155',
    cornerDotType: 'dot',
    cornerDotColor: '#334155',
    background: '#ffffff',
    logoBrand: 'wifi',
    frame: 'bottom-badge',
    frameText: 'Connect WIFI',
    frameColor: '#cbd5e1',
    frameTextColor: '#0f172a'
  },
  {
    id: 'template-location-findus',
    name: 'Location Find Us',
    desc: 'Leaf shaped corners with crimson arch card and Location pin',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#991b1b',
    cornerSquareType: 'classy',
    cornerSquareColor: '#991b1b',
    cornerDotType: 'classy',
    cornerDotColor: '#991b1b',
    background: '#ffffff',
    logoBrand: 'maps',
    frame: 'arch-card',
    frameText: 'Find us',
    frameColor: '#881337',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-appstore-download',
    name: 'App Store Download',
    desc: 'Clean ocean blue arch card with Store icons & "Download App"',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0284c7',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0284c7',
    cornerDotType: 'dot',
    cornerDotColor: '#0284c7',
    background: '#ffffff',
    logoBrand: 'apple',
    frame: 'arch-card',
    frameText: 'Download App',
    frameColor: '#0284c7',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-tripadvisor-review',
    name: 'TripAdvisor Review',
    desc: 'Emerald green arch card with TripAdvisor owl and "Write a review"',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0f172a',
    cornerSquareType: 'dot',
    cornerSquareColor: '#00af87',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'tripadvisor',
    frame: 'arch-card',
    frameText: 'Write a review',
    frameColor: '#00af87',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-soundcloud-playlist',
    name: 'SoundCloud Playlist',
    desc: 'Vibrant orange arch card with SoundCloud cloud logo',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#ea580c',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#ea580c',
    cornerDotType: 'dot',
    cornerDotColor: '#ea580c',
    background: '#ffffff',
    logoBrand: 'soundcloud',
    frame: 'arch-card',
    frameText: 'Listen Playlist',
    frameColor: '#ea580c',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-facebook-blue',
    name: 'Facebook Connect',
    desc: 'Classic Facebook brand blue with bold center icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#1877f2',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#1877f2',
    background: '#ffffff',
    logoBrand: 'facebook',
    frame: 'none'
  },
  {
    id: 'template-whatsapp-green',
    name: 'WhatsApp Direct',
    desc: 'Vibrant green WhatsApp themed dots with phone icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#25d366',
    cornerSquareType: 'square',
    cornerSquareColor: '#25d366',
    cornerDotType: 'square',
    cornerDotColor: '#25d366',
    background: '#ffffff',
    logoBrand: 'whatsapp',
    frame: 'none'
  },
  {
    id: 'template-youtube-red',
    name: 'YouTube Red Channel',
    desc: 'High contrast black and YouTube red play icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'youtube',
    frame: 'none'
  },
  {
    id: 'template-telegram-channel',
    name: 'Telegram Channel',
    desc: 'Deep navy circular badge with "telegram.me" pill',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0284c7',
    cornerSquareType: 'dot',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'dot',
    cornerDotColor: '#0284c7',
    background: '#ffffff',
    logoBrand: 'telegram',
    frame: 'circle-badge',
    frameText: 'telegram.me',
    frameColor: '#0f172a',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-audio-track',
    name: 'Audio Speaker Card',
    desc: 'Ocean blue rounded double border with audio speaker icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#0284c7',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0284c7',
    cornerDotType: 'dot',
    cornerDotColor: '#0284c7',
    background: '#ffffff',
    logoBrand: 'audio',
    frame: 'simple-box',
    frameColor: '#0284c7'
  },
  {
    id: 'template-dashed-circle',
    name: 'Dashed Circle Teal',
    desc: 'Teal dotted pattern with stylish dashed circular perimeter',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#0d9488',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0d9488',
    cornerDotType: 'dot',
    cornerDotColor: '#0284c7',
    background: '#ffffff',
    frame: 'dashed-circle',
    frameColor: '#0d9488'
  },
  {
    id: 'template-join-us',
    name: 'Join Us Brackets',
    desc: 'Pink & purple gradient with navy corner brackets and "Join us"',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#ec4899',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#ec4899',
    cornerDotType: 'dot',
    cornerDotColor: '#8b5cf6',
    background: '#ffffff',
    frame: 'corner-brackets',
    frameText: 'Join us',
    frameColor: '#1e1b4b',
    frameTextColor: '#1e1b4b'
  },
  {
    id: 'template-scanme-red',
    name: 'SCAN ME Red Brackets',
    desc: 'Red corner brackets with bold red "SCAN ME" text',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'corner-brackets',
    frameText: 'SCAN ME',
    frameColor: '#ef4444',
    frameTextColor: '#ef4444'
  },
  {
    id: 'template-wechat-black',
    name: 'WeChat Black Card',
    desc: 'Black rounded card border with WeChat green icon and "WeChat"',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#000000',
    cornerDotType: 'dot',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'wechat',
    frame: 'card-border',
    frameText: 'WeChat',
    frameColor: '#000000',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-minimal-square',
    name: 'Minimalist Square Frame',
    desc: 'Clean minimal square outline frame with extra-rounded corners',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'simple-box',
    frameColor: '#000000'
  },
  {
    id: 'template-minimal-circle',
    name: 'Minimalist Circle Frame',
    desc: 'Clean black circular ring frame',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'circle-outline',
    frameColor: '#000000'
  },
  {
    id: 'template-minimal-hexagon',
    name: 'Minimalist Hexagon Frame',
    desc: 'Clean geometric hexagon outline frame',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'hexagon-outline',
    frameColor: '#000000'
  },
  {
    id: 'template-minimal-brackets',
    name: 'Minimalist Corner Brackets',
    desc: 'Clean black corner brackets frame without text',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'corner-brackets',
    frameText: '',
    frameColor: '#000000'
  },
  {
    id: 'template-square-border',
    name: 'Thick Square Border',
    desc: 'Bold modern square card border with high contrast',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'simple-box',
    frameColor: '#000000'
  },
  {
    id: 'template-add-contacts',
    name: 'Add to Contacts Tooltip',
    desc: 'Black tooltip bubble with arrow pointer and contact logo',
    category: 'templates',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'contact',
    frame: 'tooltip-bubble',
    frameText: 'Add to contacts',
    frameColor: '#18181b',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-contact-me-circle',
    name: 'Contact Me Circle',
    desc: 'Red circular ring frame with "Contact me" pill and avatar icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#ef4444',
    cornerSquareType: 'dot',
    cornerSquareColor: '#ef4444',
    cornerDotType: 'dot',
    cornerDotColor: '#ef4444',
    background: '#ffffff',
    logoBrand: 'contact',
    frame: 'circle-badge',
    frameText: 'Contact me',
    frameColor: '#ef4444',
    frameTextColor: '#ffffff'
  },
  {
    id: 'template-target-radar',
    name: 'Radar Target Concentric',
    desc: 'High tech radar circular target pattern with contact icon',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#000000',
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    logoBrand: 'contact',
    frame: 'dashed-circle',
    frameColor: '#ef4444'
  },
  {
    id: 'template-phone-callme',
    name: 'Smartphone Call Me',
    desc: 'Green mobile smartphone frame with speaker notch and "Call me" button',
    category: 'templates',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#16a34a',
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#16a34a',
    cornerDotType: 'dot',
    cornerDotColor: '#16a34a',
    background: '#ffffff',
    logoBrand: 'whatsapp',
    frame: 'phone',
    frameText: 'Call me',
    frameColor: '#16a34a',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 1. COOL PRESETS (8 Designs)
  // ==========================================
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    desc: 'Sleek dark gradient with glowing cyan eyes',
    category: 'cool',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#38bdf8',
    dotsGradientColor: '#818cf8',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#38bdf8',
    cornerDotType: 'dot',
    cornerDotColor: '#818cf8',
    background: '#0f172a',
    frame: 'none'
  },
  {
    id: 'cyber-neon',
    name: 'Cyberpunk Neon',
    desc: 'Vibrant magenta and violet glow',
    category: 'cool',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#ec4899',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'dot',
    cornerSquareColor: '#ec4899',
    cornerDotType: 'dot',
    cornerDotColor: '#8b5cf6',
    background: '#09090b',
    frame: 'card-border',
    frameText: 'SCAN ME',
    frameColor: '#ec4899',
    frameTextColor: '#ffffff'
  },
  {
    id: 'sunset-vibrant',
    name: 'Sunset Glow',
    desc: 'Warm orange and coral red gradient',
    category: 'cool',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#e11d48',
    cornerDotType: 'dot',
    cornerDotColor: '#f97316',
    background: '#fff7ed',
    frame: 'top-banner',
    frameText: 'DISCOVER MORE',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-ocean',
    name: 'Deep Ocean Blue',
    desc: 'Mystic aquamarine and midnight teal gradient',
    category: 'cool',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#06b6d4',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'classy',
    cornerSquareColor: '#0891b2',
    cornerDotType: 'dot',
    cornerDotColor: '#38bdf8',
    background: '#042f2e',
    frame: 'bottom-badge',
    frameText: 'DISCOVER',
    frameColor: '#0891b2',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-aurora',
    name: 'Aurora Borealis',
    desc: 'Electric green and celestial teal glow',
    category: 'cool',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#06b6d4',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#10b981',
    cornerDotType: 'dot',
    cornerDotColor: '#2dd4bf',
    background: '#022c22',
    frame: 'none'
  },
  {
    id: 'cool-carbon',
    name: 'Carbon Fiber Slate',
    desc: 'High-tech dark carbon weave',
    category: 'cool',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#94a3b8',
    dotsGradientColor: '#cbd5e1',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#f8fafc',
    cornerDotType: 'square',
    cornerDotColor: '#cbd5e1',
    background: '#0f172a',
    frame: 'card-border',
    frameText: 'SCAN CODE',
    frameColor: '#475569',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cool-nebula',
    name: 'Galaxy Nebula',
    desc: 'Radial cosmic pink and violet starlight',
    category: 'cool',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#f43f5e',
    dotsGradientColor: '#8b5cf6',
    gradientType: 'radial',
    gradientRotation: 0,
    cornerSquareType: 'classy',
    cornerSquareColor: '#f43f5e',
    cornerDotType: 'classy',
    cornerDotColor: '#fb7185',
    background: '#1e1b4b',
    frame: 'none'
  },
  {
    id: 'cool-ice',
    name: 'Frosted Glacial Ice',
    desc: 'Chilled ice blue on crisp porcelain',
    category: 'cool',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#38bdf8',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0284c7',
    cornerDotType: 'dot',
    cornerDotColor: '#7dd3fc',
    background: '#f0f9ff',
    frame: 'bottom-badge',
    frameText: 'OPEN LINK',
    frameColor: '#0284c7',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 2. PROFESSIONAL PRESETS (8 Designs)
  // ==========================================
  {
    id: 'emerald-glass',
    name: 'Emerald Glass',
    desc: 'Fresh mint and emerald green aesthetic',
    category: 'professional',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#10b981',
    dotsGradientColor: '#065f46',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'classy',
    cornerSquareColor: '#059669',
    cornerDotType: 'classy',
    cornerDotColor: '#10b981',
    background: '#f0fdf4',
    frame: 'bottom-badge',
    frameText: 'SCAN TO OPEN',
    frameColor: '#059669',
    frameTextColor: '#ffffff'
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    desc: 'Luxury metallic gold on deep onyx',
    category: 'professional',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#f59e0b',
    dotsGradientColor: '#d97706',
    gradientType: 'radial',
    gradientRotation: 0,
    cornerSquareType: 'classy',
    cornerSquareColor: '#f59e0b',
    cornerDotType: 'classy',
    cornerDotColor: '#fbbf24',
    background: '#18181b',
    frame: 'none'
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Clean',
    desc: 'Trustworthy navy and royal blue palette',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#1e40af',
    dotsGradientColor: '#3b82f6',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#1e3a8a',
    cornerDotType: 'dot',
    cornerDotColor: '#2563eb',
    background: '#ffffff',
    frame: 'bottom-badge',
    frameText: 'SCAN FOR INFO',
    frameColor: '#1e40af',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-slate',
    name: 'Executive Slate',
    desc: 'Sophisticated charcoal grey for corporate documents',
    category: 'professional',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#334155',
    dotsGradientColor: '#334155',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'square',
    cornerDotColor: '#475569',
    background: '#f8fafc',
    frame: 'none'
  },
  {
    id: 'professional-wine',
    name: 'Bordeaux Burgundy',
    desc: 'Rich wine red and gold accent luxury branding',
    category: 'professional',
    dotsType: 'classy',
    dotsColorType: 'gradient',
    dotsColor: '#881337',
    dotsGradientColor: '#be123c',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#881337',
    cornerDotType: 'classy',
    cornerDotColor: '#fb7185',
    background: '#fff1f2',
    frame: 'bottom-badge',
    frameText: 'EXCLUSIVE ACCESS',
    frameColor: '#881337',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-silver',
    name: 'Platinum Executive',
    desc: 'Silver metallic sheen on deep slate background',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#e2e8f0',
    dotsGradientColor: '#94a3b8',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#cbd5e1',
    cornerDotType: 'dot',
    cornerDotColor: '#ffffff',
    background: '#0f172a',
    frame: 'card-border',
    frameText: 'OFFICIAL RECORD',
    frameColor: '#334155',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-rosegold',
    name: 'Luxe Rose Gold',
    desc: 'Warm rose champagne tone for boutique products',
    category: 'professional',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#fb7185',
    dotsGradientColor: '#f43f5e',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'classy',
    cornerSquareColor: '#e11d48',
    cornerDotType: 'classy',
    cornerDotColor: '#fda4af',
    background: '#fff1f2',
    frame: 'bottom-badge',
    frameText: 'SCAN TO VIEW MENU',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff'
  },
  {
    id: 'professional-teal',
    name: 'Enterprise Teal',
    desc: 'Modern healthcare & finance teal theme',
    category: 'professional',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#0f766e',
    dotsGradientColor: '#14b8a6',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0f766e',
    cornerDotType: 'dot',
    cornerDotColor: '#2dd4bf',
    background: '#f0fdfa',
    frame: 'bottom-badge',
    frameText: 'VERIFIED PORTAL',
    frameColor: '#0f766e',
    frameTextColor: '#ffffff'
  },

  // ==========================================
  // 3. SIMPLE PRESETS (8 Designs)
  // ==========================================
  {
    id: 'minimalist-mono',
    name: 'Minimalist Mono',
    desc: 'Crisp high-contrast pure black and white',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#000000',
    dotsGradientColor: '#000000',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#000000',
    cornerDotType: 'square',
    cornerDotColor: '#000000',
    background: '#ffffff',
    frame: 'none'
  },
  {
    id: 'pastel-violet',
    name: 'Pastel Lavender',
    desc: 'Soft lilac and purple for modern brands',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#8b5cf6',
    dotsGradientColor: '#a855f7',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#7c3aed',
    cornerDotType: 'dot',
    cornerDotColor: '#a855f7',
    background: '#faf5ff',
    frame: 'bottom-badge',
    frameText: 'SCAN ME',
    frameColor: '#7c3aed',
    frameTextColor: '#ffffff'
  },
  {
    id: 'simple-peach',
    name: 'Pastel Peach',
    desc: 'Warm cream and soft apricot tone',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#ea580c',
    dotsGradientColor: '#ea580c',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#c2410c',
    cornerDotType: 'dot',
    cornerDotColor: '#f97316',
    background: '#fff7ed',
    frame: 'none'
  },
  {
    id: 'simple-mint',
    name: 'Clean Sage Mint',
    desc: 'Gentle organic green on soft off-white',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#15803d',
    dotsGradientColor: '#15803d',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#166534',
    cornerDotType: 'dot',
    cornerDotColor: '#22c55e',
    background: '#f0fdf4',
    frame: 'none'
  },
  {
    id: 'simple-charcoal',
    name: 'Charcoal Minimal',
    desc: 'Clean dark slate on ivory grey paper',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#1e293b',
    dotsGradientColor: '#1e293b',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#0f172a',
    cornerDotType: 'square',
    cornerDotColor: '#334155',
    background: '#f1f5f9',
    frame: 'none'
  },
  {
    id: 'simple-sky',
    name: 'Soft Sky Blue',
    desc: 'Light blue tones for subtle print stickers',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#0284c7',
    dotsGradientColor: '#0284c7',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#0369a1',
    cornerDotType: 'dot',
    cornerDotColor: '#38bdf8',
    background: '#f0f9ff',
    frame: 'none'
  },
  {
    id: 'simple-dark-mono',
    name: 'Dark Mode Pure',
    desc: 'Crisp white dots on dark night surface',
    category: 'simple',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#ffffff',
    dotsGradientColor: '#ffffff',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#ffffff',
    cornerDotType: 'square',
    cornerDotColor: '#ffffff',
    background: '#090d16',
    frame: 'none'
  },
  {
    id: 'simple-rose',
    name: 'Soft Rose Quartz',
    desc: 'Elegant muted pink on pale rose background',
    category: 'simple',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor: '#e11d48',
    dotsGradientColor: '#e11d48',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#be123c',
    cornerDotType: 'dot',
    cornerDotColor: '#fb7185',
    background: '#fff1f2',
    frame: 'none'
  },

  // ==========================================
  // 4. GAMING PRESETS (8 Designs)
  // ==========================================
  {
    id: 'gaming-razer',
    name: 'Toxic Chroma Green',
    desc: 'Electric esports neon green on stealth black',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#22c55e',
    dotsGradientColor: '#10b981',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'square',
    cornerSquareColor: '#22c55e',
    cornerDotType: 'square',
    cornerDotColor: '#4ade80',
    background: '#050505',
    frame: 'card-border',
    frameText: 'JOIN LOBBY',
    frameColor: '#22c55e',
    frameTextColor: '#000000'
  },
  {
    id: 'gaming-ps',
    name: 'Console Blue LED',
    desc: 'Royal gaming blue and cyan controller vibe',
    category: 'gaming',
    dotsType: 'dots',
    dotsColorType: 'gradient',
    dotsColor: '#3b82f6',
    dotsGradientColor: '#06b6d4',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'dot',
    cornerSquareColor: '#2563eb',
    cornerDotType: 'dot',
    cornerDotColor: '#60a5fa',
    background: '#090d16',
    frame: 'bottom-badge',
    frameText: 'PRESS START',
    frameColor: '#2563eb',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-rog',
    name: 'ROG Crimson Core',
    desc: 'Aggressive gaming red and metallic obsidian',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#ef4444',
    dotsGradientColor: '#b91c1c',
    gradientType: 'linear',
    gradientRotation: 135,
    cornerSquareType: 'square',
    cornerSquareColor: '#dc2626',
    cornerDotType: 'square',
    cornerDotColor: '#fca5a5',
    background: '#09090b',
    frame: 'top-banner',
    frameText: 'LEVEL UP',
    frameColor: '#dc2626',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-cyberpunk2077',
    name: 'Night City Yellow',
    desc: 'Futuristic high-voltage yellow & dark gunmetal',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor: '#facc15',
    dotsGradientColor: '#facc15',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'square',
    cornerSquareColor: '#eab308',
    cornerDotType: 'square',
    cornerDotColor: '#fef08a',
    background: '#18181b',
    frame: 'bottom-badge',
    frameText: 'HACK DATA',
    frameColor: '#facc15',
    frameTextColor: '#000000'
  },
  {
    id: 'gaming-twitch',
    name: 'Streamer Purple',
    desc: 'Vibrant livestream purple & violet starlight',
    category: 'gaming',
    dotsType: 'rounded',
    dotsColorType: 'gradient',
    dotsColor: '#9333ea',
    dotsGradientColor: '#c084fc',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#7e22ce',
    cornerDotType: 'dot',
    cornerDotColor: '#e9d5ff',
    background: '#1e1b4b',
    frame: 'bottom-badge',
    frameText: 'WATCH LIVE',
    frameColor: '#9333ea',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-retro-arcade',
    name: 'Retro 8-Bit Arcade',
    desc: 'Pixelated orange and yellow 80s arcade vibe',
    category: 'gaming',
    dotsType: 'square',
    dotsColorType: 'gradient',
    dotsColor: '#f97316',
    dotsGradientColor: '#facc15',
    gradientType: 'linear',
    gradientRotation: 90,
    cornerSquareType: 'square',
    cornerSquareColor: '#ea580c',
    cornerDotType: 'square',
    cornerDotColor: '#fde047',
    background: '#172554',
    frame: 'card-border',
    frameText: 'INSERT COIN',
    frameColor: '#f97316',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-pipboy',
    name: 'Fallout Terminal Green',
    desc: 'Retro CRT phosphor green on dark bunker monitor',
    category: 'gaming',
    dotsType: 'dots',
    dotsColorType: 'single',
    dotsColor: '#4ade80',
    dotsGradientColor: '#4ade80',
    gradientType: 'linear',
    gradientRotation: 0,
    cornerSquareType: 'dot',
    cornerSquareColor: '#22c55e',
    cornerDotType: 'dot',
    cornerDotColor: '#86efac',
    background: '#022c22',
    frame: 'top-banner',
    frameText: 'VAULT TEC DATA',
    frameColor: '#15803d',
    frameTextColor: '#ffffff'
  },
  {
    id: 'gaming-discord',
    name: 'Discord Squad',
    desc: 'Blurple & dark chat room gamer aesthetic',
    category: 'gaming',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient',
    dotsColor: '#5865f2',
    dotsGradientColor: '#818cf8',
    gradientType: 'linear',
    gradientRotation: 45,
    cornerSquareType: 'extra-rounded',
    cornerSquareColor: '#5865f2',
    cornerDotType: 'dot',
    cornerDotColor: '#c7d2fe',
    background: '#1e1f22',
    frame: 'bottom-badge',
    frameText: 'JOIN DISCORD',
    frameColor: '#5865f2',
    frameTextColor: '#ffffff'
  }
];